azure:
  storage:
    account-name: nebdeveuwplg01st
    blob-endpoint: https://nebdeveuwplg01st.blob.core.windows.net
    account-key: p0HkfWjDDe7w64kwuojQmrSfNdfL6kUSX5j/3QHBiCCj+lLcdt55peik8W3a/NRtveTrCkAbdKVTEL8OfG5WHw==